// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/budget_service.proto

package budgetpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Budget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerUserId   int64                  `protobuf:"varint,3,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Budget) Reset() {
	*x = Budget{}
	mi := &file_api_proto_budget_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Budget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Budget) ProtoMessage() {}

func (x *Budget) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_budget_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Budget.ProtoReflect.Descriptor instead.
func (*Budget) Descriptor() ([]byte, []int) {
	return file_api_proto_budget_service_proto_rawDescGZIP(), []int{0}
}

func (x *Budget) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Budget) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Budget) GetOwnerUserId() int64 {
	if x != nil {
		return x.OwnerUserId
	}
	return 0
}

func (x *Budget) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Budget) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type BudgetPeriod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BudgetId      int64                  `protobuf:"varint,2,opt,name=budget_id,json=budgetId,proto3" json:"budget_id,omitempty"`
	PeriodStart   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetPeriod) Reset() {
	*x = BudgetPeriod{}
	mi := &file_api_proto_budget_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetPeriod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetPeriod) ProtoMessage() {}

func (x *BudgetPeriod) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_budget_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetPeriod.ProtoReflect.Descriptor instead.
func (*BudgetPeriod) Descriptor() ([]byte, []int) {
	return file_api_proto_budget_service_proto_rawDescGZIP(), []int{1}
}

func (x *BudgetPeriod) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BudgetPeriod) GetBudgetId() int64 {
	if x != nil {
		return x.BudgetId
	}
	return 0
}

func (x *BudgetPeriod) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *BudgetPeriod) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

func (x *BudgetPeriod) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BudgetPeriod) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type PeriodLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PeriodId      int64                  `protobuf:"varint,2,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	CurrencyId    int64                  `protobuf:"varint,3,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	LimitAmount   string                 `protobuf:"bytes,4,opt,name=limit_amount,json=limitAmount,proto3" json:"limit_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeriodLimit) Reset() {
	*x = PeriodLimit{}
	mi := &file_api_proto_budget_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeriodLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeriodLimit) ProtoMessage() {}

func (x *PeriodLimit) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_budget_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeriodLimit.ProtoReflect.Descriptor instead.
func (*PeriodLimit) Descriptor() ([]byte, []int) {
	return file_api_proto_budget_service_proto_rawDescGZIP(), []int{2}
}

func (x *PeriodLimit) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PeriodLimit) GetPeriodId() int64 {
	if x != nil {
		return x.PeriodId
	}
	return 0
}

func (x *PeriodLimit) GetCurrencyId() int64 {
	if x != nil {
		return x.CurrencyId
	}
	return 0
}

func (x *PeriodLimit) GetLimitAmount() string {
	if x != nil {
		return x.LimitAmount
	}
	return ""
}

type CreateBudgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBudgetRequest) Reset() {
	*x = CreateBudgetRequest{}
	mi := &file_api_proto_budget_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBudgetRequest) ProtoMessage() {}

func (x *CreateBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_budget_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBudgetRequest.ProtoReflect.Descriptor instead.
func (*CreateBudgetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_budget_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBudgetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListAvailableBudgetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAvailableBudgetsRequest) Reset() {
	*x = ListAvailableBudgetsRequest{}
	mi := &file_api_proto_budget_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAvailableBudgetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailableBudgetsRequest) ProtoMessage() {}

func (x *ListAvailableBudgetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_budget_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailableBudgetsRequest.ProtoReflect.Descriptor instead.
func (*ListAvailableBudgetsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_budget_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListAvailableBudgetsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListAvailableBudgetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Budgets       []*Budget              `protobuf:"bytes,1,rep,name=budgets,proto3" json:"budgets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAvailableBudgetsResponse) Reset() {
	*x = ListAvailableBudgetsResponse{}
	mi := &file_api_proto_budget_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAvailableBudgetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailableBudgetsResponse) ProtoMessage() {}

func (x *ListAvailableBudgetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_budget_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailableBudgetsResponse.ProtoReflect.Descriptor instead.
func (*ListAvailableBudgetsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_budget_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListAvailableBudgetsResponse) GetBudgets() []*Budget {
	if x != nil {
		return x.Budgets
	}
	return nil
}

type CreatePeriodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BudgetId      int64                  `protobuf:"varint,1,opt,name=budget_id,json=budgetId,proto3" json:"budget_id,omitempty"`
	PeriodStart   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePeriodRequest) Reset() {
	*x = CreatePeriodRequest{}
	mi := &file_api_proto_budget_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePeriodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePeriodRequest) ProtoMessage() {}

func (x *CreatePeriodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_budget_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePeriodRequest.ProtoReflect.Descriptor instead.
func (*CreatePeriodRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_budget_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePeriodRequest) GetBudgetId() int64 {
	if x != nil {
		return x.BudgetId
	}
	return 0
}

func (x *CreatePeriodRequest) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *CreatePeriodRequest) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

type ListPeriodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BudgetId      int64                  `protobuf:"varint,1,opt,name=budget_id,json=budgetId,proto3" json:"budget_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeriodsRequest) Reset() {
	*x = ListPeriodsRequest{}
	mi := &file_api_proto_budget_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeriodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeriodsRequest) ProtoMessage() {}

func (x *ListPeriodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_budget_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeriodsRequest.ProtoReflect.Descriptor instead.
func (*ListPeriodsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_budget_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListPeriodsRequest) GetBudgetId() int64 {
	if x != nil {
		return x.BudgetId
	}
	return 0
}

type ListPeriodsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Periods       []*BudgetPeriod        `protobuf:"bytes,1,rep,name=periods,proto3" json:"periods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeriodsResponse) Reset() {
	*x = ListPeriodsResponse{}
	mi := &file_api_proto_budget_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeriodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeriodsResponse) ProtoMessage() {}

func (x *ListPeriodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_budget_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeriodsResponse.ProtoReflect.Descriptor instead.
func (*ListPeriodsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_budget_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListPeriodsResponse) GetPeriods() []*BudgetPeriod {
	if x != nil {
		return x.Periods
	}
	return nil
}

type SetPeriodLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeriodId      int64                  `protobuf:"varint,1,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	CurrencyId    int64                  `protobuf:"varint,2,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	LimitAmount   string                 `protobuf:"bytes,3,opt,name=limit_amount,json=limitAmount,proto3" json:"limit_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPeriodLimitRequest) Reset() {
	*x = SetPeriodLimitRequest{}
	mi := &file_api_proto_budget_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPeriodLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPeriodLimitRequest) ProtoMessage() {}

func (x *SetPeriodLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_budget_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPeriodLimitRequest.ProtoReflect.Descriptor instead.
func (*SetPeriodLimitRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_budget_service_proto_rawDescGZIP(), []int{9}
}

func (x *SetPeriodLimitRequest) GetPeriodId() int64 {
	if x != nil {
		return x.PeriodId
	}
	return 0
}

func (x *SetPeriodLimitRequest) GetCurrencyId() int64 {
	if x != nil {
		return x.CurrencyId
	}
	return 0
}

func (x *SetPeriodLimitRequest) GetLimitAmount() string {
	if x != nil {
		return x.LimitAmount
	}
	return ""
}

type GrantRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BudgetId      int64                  `protobuf:"varint,2,opt,name=budget_id,json=budgetId,proto3" json:"budget_id,omitempty"`
	RoleCode      string                 `protobuf:"bytes,3,opt,name=role_code,json=roleCode,proto3" json:"role_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantRoleRequest) Reset() {
	*x = GrantRoleRequest{}
	mi := &file_api_proto_budget_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantRoleRequest) ProtoMessage() {}

func (x *GrantRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_budget_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantRoleRequest.ProtoReflect.Descriptor instead.
func (*GrantRoleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_budget_service_proto_rawDescGZIP(), []int{10}
}

func (x *GrantRoleRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GrantRoleRequest) GetBudgetId() int64 {
	if x != nil {
		return x.BudgetId
	}
	return 0
}

func (x *GrantRoleRequest) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

type GrantRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantRoleResponse) Reset() {
	*x = GrantRoleResponse{}
	mi := &file_api_proto_budget_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantRoleResponse) ProtoMessage() {}

func (x *GrantRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_budget_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantRoleResponse.ProtoReflect.Descriptor instead.
func (*GrantRoleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_budget_service_proto_rawDescGZIP(), []int{11}
}

func (x *GrantRoleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_proto_budget_service_proto protoreflect.FileDescriptor

const file_api_proto_budget_service_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/budget_service.proto\x12\tbudget.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc6\x01\n" +
	"\x06Budget\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\rowner_user_id\x18\x03 \x01(\x03R\vownerUserId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xab\x02\n" +
	"\fBudgetPeriod\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tbudget_id\x18\x02 \x01(\x03R\bbudgetId\x12=\n" +
	"\fperiod_start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"~\n" +
	"\vPeriodLimit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tperiod_id\x18\x02 \x01(\x03R\bperiodId\x12\x1f\n" +
	"\vcurrency_id\x18\x03 \x01(\x03R\n" +
	"currencyId\x12!\n" +
	"\flimit_amount\x18\x04 \x01(\tR\vlimitAmount\")\n" +
	"\x13CreateBudgetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"6\n" +
	"\x1bListAvailableBudgetsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"K\n" +
	"\x1cListAvailableBudgetsResponse\x12+\n" +
	"\abudgets\x18\x01 \x03(\v2\x11.budget.v1.BudgetR\abudgets\"\xac\x01\n" +
	"\x13CreatePeriodRequest\x12\x1b\n" +
	"\tbudget_id\x18\x01 \x01(\x03R\bbudgetId\x12=\n" +
	"\fperiod_start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\"1\n" +
	"\x12ListPeriodsRequest\x12\x1b\n" +
	"\tbudget_id\x18\x01 \x01(\x03R\bbudgetId\"H\n" +
	"\x13ListPeriodsResponse\x121\n" +
	"\aperiods\x18\x01 \x03(\v2\x17.budget.v1.BudgetPeriodR\aperiods\"x\n" +
	"\x15SetPeriodLimitRequest\x12\x1b\n" +
	"\tperiod_id\x18\x01 \x01(\x03R\bperiodId\x12\x1f\n" +
	"\vcurrency_id\x18\x02 \x01(\x03R\n" +
	"currencyId\x12!\n" +
	"\flimit_amount\x18\x03 \x01(\tR\vlimitAmount\"e\n" +
	"\x10GrantRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tbudget_id\x18\x02 \x01(\x03R\bbudgetId\x12\x1b\n" +
	"\trole_code\x18\x03 \x01(\tR\broleCode\"-\n" +
	"\x11GrantRoleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xe6\x03\n" +
	"\rBudgetService\x12A\n" +
	"\fCreateBudget\x12\x1e.budget.v1.CreateBudgetRequest\x1a\x11.budget.v1.Budget\x12g\n" +
	"\x14ListAvailableBudgets\x12&.budget.v1.ListAvailableBudgetsRequest\x1a'.budget.v1.ListAvailableBudgetsResponse\x12G\n" +
	"\fCreatePeriod\x12\x1e.budget.v1.CreatePeriodRequest\x1a\x17.budget.v1.BudgetPeriod\x12L\n" +
	"\vListPeriods\x12\x1d.budget.v1.ListPeriodsRequest\x1a\x1e.budget.v1.ListPeriodsResponse\x12J\n" +
	"\x0eSetPeriodLimit\x12 .budget.v1.SetPeriodLimitRequest\x1a\x16.budget.v1.PeriodLimit\x12F\n" +
	"\tGrantRole\x12\x1b.budget.v1.GrantRoleRequest\x1a\x1c.budget.v1.GrantRoleResponseB\x14Z\x12api/proto/budgetpbb\x06proto3"

var (
	file_api_proto_budget_service_proto_rawDescOnce sync.Once
	file_api_proto_budget_service_proto_rawDescData []byte
)

func file_api_proto_budget_service_proto_rawDescGZIP() []byte {
	file_api_proto_budget_service_proto_rawDescOnce.Do(func() {
		file_api_proto_budget_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_budget_service_proto_rawDesc), len(file_api_proto_budget_service_proto_rawDesc)))
	})
	return file_api_proto_budget_service_proto_rawDescData
}

var file_api_proto_budget_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_proto_budget_service_proto_goTypes = []any{
	(*Budget)(nil),                       // 0: budget.v1.Budget
	(*BudgetPeriod)(nil),                 // 1: budget.v1.BudgetPeriod
	(*PeriodLimit)(nil),                  // 2: budget.v1.PeriodLimit
	(*CreateBudgetRequest)(nil),          // 3: budget.v1.CreateBudgetRequest
	(*ListAvailableBudgetsRequest)(nil),  // 4: budget.v1.ListAvailableBudgetsRequest
	(*ListAvailableBudgetsResponse)(nil), // 5: budget.v1.ListAvailableBudgetsResponse
	(*CreatePeriodRequest)(nil),          // 6: budget.v1.CreatePeriodRequest
	(*ListPeriodsRequest)(nil),           // 7: budget.v1.ListPeriodsRequest
	(*ListPeriodsResponse)(nil),          // 8: budget.v1.ListPeriodsResponse
	(*SetPeriodLimitRequest)(nil),        // 9: budget.v1.SetPeriodLimitRequest
	(*GrantRoleRequest)(nil),             // 10: budget.v1.GrantRoleRequest
	(*GrantRoleResponse)(nil),            // 11: budget.v1.GrantRoleResponse
	(*timestamppb.Timestamp)(nil),        // 12: google.protobuf.Timestamp
}
var file_api_proto_budget_service_proto_depIdxs = []int32{
	12, // 0: budget.v1.Budget.created_at:type_name -> google.protobuf.Timestamp
	12, // 1: budget.v1.Budget.updated_at:type_name -> google.protobuf.Timestamp
	12, // 2: budget.v1.BudgetPeriod.period_start:type_name -> google.protobuf.Timestamp
	12, // 3: budget.v1.BudgetPeriod.period_end:type_name -> google.protobuf.Timestamp
	12, // 4: budget.v1.BudgetPeriod.created_at:type_name -> google.protobuf.Timestamp
	12, // 5: budget.v1.BudgetPeriod.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 6: budget.v1.ListAvailableBudgetsResponse.budgets:type_name -> budget.v1.Budget
	12, // 7: budget.v1.CreatePeriodRequest.period_start:type_name -> google.protobuf.Timestamp
	12, // 8: budget.v1.CreatePeriodRequest.period_end:type_name -> google.protobuf.Timestamp
	1,  // 9: budget.v1.ListPeriodsResponse.periods:type_name -> budget.v1.BudgetPeriod
	3,  // 10: budget.v1.BudgetService.CreateBudget:input_type -> budget.v1.CreateBudgetRequest
	4,  // 11: budget.v1.BudgetService.ListAvailableBudgets:input_type -> budget.v1.ListAvailableBudgetsRequest
	6,  // 12: budget.v1.BudgetService.CreatePeriod:input_type -> budget.v1.CreatePeriodRequest
	7,  // 13: budget.v1.BudgetService.ListPeriods:input_type -> budget.v1.ListPeriodsRequest
	9,  // 14: budget.v1.BudgetService.SetPeriodLimit:input_type -> budget.v1.SetPeriodLimitRequest
	10, // 15: budget.v1.BudgetService.GrantRole:input_type -> budget.v1.GrantRoleRequest
	0,  // 16: budget.v1.BudgetService.CreateBudget:output_type -> budget.v1.Budget
	5,  // 17: budget.v1.BudgetService.ListAvailableBudgets:output_type -> budget.v1.ListAvailableBudgetsResponse
	1,  // 18: budget.v1.BudgetService.CreatePeriod:output_type -> budget.v1.BudgetPeriod
	8,  // 19: budget.v1.BudgetService.ListPeriods:output_type -> budget.v1.ListPeriodsResponse
	2,  // 20: budget.v1.BudgetService.SetPeriodLimit:output_type -> budget.v1.PeriodLimit
	11, // 21: budget.v1.BudgetService.GrantRole:output_type -> budget.v1.GrantRoleResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_proto_budget_service_proto_init() }
func file_api_proto_budget_service_proto_init() {
	if File_api_proto_budget_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_budget_service_proto_rawDesc), len(file_api_proto_budget_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_budget_service_proto_goTypes,
		DependencyIndexes: file_api_proto_budget_service_proto_depIdxs,
		MessageInfos:      file_api_proto_budget_service_proto_msgTypes,
	}.Build()
	File_api_proto_budget_service_proto = out.File
	file_api_proto_budget_service_proto_goTypes = nil
	file_api_proto_budget_service_proto_depIdxs = nil
}
